list:
  七森中☆ごらく部:
    - 七森中☆ごらく部
    - ごらく部
  三上枝織:
    - ごらく部
  大坪由佳:
    - ごらく部
  津田美波:
    - ごらく部
    - 津田ちゃん
    - つだちゃん
  大久保瑠美:
    - ごらく部
  μ's:
    - μ's
    - ラブライブ
    - ラブライブ！
  高坂穂乃果:
    - 高坂穂乃果
    - 穂乃果
    - ほのか
  絢瀬絵里:
    - 絢瀬絵里
    - 絵里
    - えりち
    - エリーチカ
    - えりーちか
  南ことり:
    - 南ことり
    - ことり
    - ちゅんちゅん
    - (・8・)
  園田海未:
    - 園田海未
    - 海未
    - うみちゃん
    - ウミチャー
    - ｳﾐﾁｬｰ
    - うみみ
    - うみみくん
  小泉花陽:
    - 小泉花陽
    - 花陽
    - はなよ
    - ぱな
    - ぱなよ
    - かよちん
  星空凛:
    - 星空凛
    - りんちゃん
    - 凛ちゃん
  西木野真姫:
    - 西木野真姫
    - 真姫
    - まきちゃん
  東條希:
    - 東條希
    - 希
    - のんちゃん
  矢澤にこ:
    - 矢澤にこ
    - にこ
    - にこにー
    - にこちゃん
    - にこにこにー
    - 世界の矢澤
  涼風青葉:
    - 涼風青葉
    - 青葉
    - NEWGAME
    - あおっち
    - 青葉ちゃん
  Aqours:
    - Aqours
    - アクア
    - サンシャイン
  渋谷凛:
    - 渋谷凛
    - しぶりん
  島村卯月:
    - 島村卯月
    - しまむー
  本田未央:
    - 本田未央
    - ちゃんみお
